CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  pro_time TIMESTAMP,
  register_time TIMESTAMP DEFAULT NOW(),
  banned_time TIMESTAMP
);
